// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// broadcaster is an autogenerated mock type for the broadcaster type
type broadcaster struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: userID, data
func (_m *broadcaster) Broadcast(userID string, data []byte) {
	_m.Called(userID, data)
}
