// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import internal "sse/internal"
import mock "github.com/stretchr/testify/mock"

// connectedUserFinder is an autogenerated mock type for the connectedUserFinder type
type connectedUserFinder struct {
	mock.Mock
}

// FindConnectedUser provides a mock function with given fields: userID
func (_m *connectedUserFinder) FindConnectedUser(userID string) *internal.UserInfo {
	ret := _m.Called(userID)

	var r0 *internal.UserInfo
	if rf, ok := ret.Get(0).(func(string) *internal.UserInfo); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.UserInfo)
		}
	}

	return r0
}
