// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import internal "sse/internal"
import mock "github.com/stretchr/testify/mock"

// connectedUserAdderRemover is an autogenerated mock type for the connectedUserAdderRemover type
type ConnectedUserAdderRemover struct {
	mock.Mock
}

// AddConnectedUser provides a mock function with given fields: ui
func (_m *ConnectedUserAdderRemover) AddConnectedUser(ui *internal.UserInfo) {
	_m.Called(ui)
}

// RemoveConnectedUser provides a mock function with given fields: ui
func (_m *ConnectedUserAdderRemover) RemoveConnectedUser(ui *internal.UserInfo) {
	_m.Called(ui)
}
