// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// errorDebugLogger is an autogenerated mock type for the errorDebugLogger type
type ErrorDebugLogger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message, fields
func (_m *ErrorDebugLogger) Debug(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: message, fields
func (_m *ErrorDebugLogger) Error(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}
