// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message, fields
func (_m *Logger) Debug(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: message, fields
func (_m *Logger) Error(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: message, fields
func (_m *Logger) Info(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}

// UpdateUuid provides a mock function with given fields: _a0
func (_m *Logger) UpdateUuid(_a0 uuid.UUID) {
	_m.Called(_a0)
}

// Warning provides a mock function with given fields: message, fields
func (_m *Logger) Warning(message string, fields ...map[string]interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, fields)
	_m.Called(_ca...)
}
