// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import internal "sse/internal"
import mock "github.com/stretchr/testify/mock"

// userInfoFromHttpRequestParser is an autogenerated mock type for the userInfoFromHttpRequestParser type
type UserInfoFromHttpRequestParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: r
func (_m *UserInfoFromHttpRequestParser) Parse(r *http.Request) (*internal.UserInfo, error) {
	ret := _m.Called(r)

	var r0 *internal.UserInfo
	if rf, ok := ret.Get(0).(func(*http.Request) *internal.UserInfo); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
